service: employee-api-${env:DEPLOYMENT_NAME}
frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  runtime: nodejs16.x
  region: ${env.AWS_REGION}
  


functions:
  fetchAllEmployees:
    handler: handler.fetchAllEmployees
    events:
      - httpApi:
          path: /
          method: get

  registerEmployees:
    handler: handler.registerEmployees
    events:
      - httpApi:
          path: /registerEmployee
          method: post


  updateEmployeeById:
    handler: handler.updateEmployeeById
    events:
      - httpApi:
          path: /updateEmployeeById/{id}
          method: put


  deleteEmployeeById:
    handler: handler.deleteEmployeeById
    events:
      - httpApi:
          path: /deleteEmployeeById/{id}
          method: delete

