name: Deploy_Lambda

on:
  create:
    tags:
    - v*

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

      - name: npm install
        env:
          CI: true
        run: |
          npm ci

      - name: deploy
        run: |
        npx build handler.js  // create build
        zip -j deploy.zip   // create zip
        aws lambda update-function-code --function-name=lambda-gh-zip-file=fileb://deploy.zip

